### ISSUE TITLE
colours.txt?

### ISSUE THREAD

**Issue by sbrl** [davisonio/darkage#14]
Hello,

Does this mod have a pre-generated `colours.txt` for this mod? I'd like to add it to my existing colours.txt to quieten all these unknown node messages I keep getting :P

**Comment by davisonio** [comment]
Hey this doesn't have this, you can use autogenerating colours.txt from here: https://github.com/minetest/minetestmapper/blob/master/autogenerating-colors.txt

**Comment by sbrl** [comment]
Ah, yeah! I remember that, @davisonio. I've run it once already, but it requires that you disable the mod sandbox in order to run it. I'm just curious to know if there's a pre-generated one for the _darkage_ mod so I don't have to bother :P

**Comment by davisonio** [comment]
Don't have a pre-generated one unfortunately!

**Comment by sbrl** [comment]
Oh dear!

Is it possible to generate one at all?

**Comment by davisonio** [comment]
This script should do that: https://github.com/minetest/minetestmapper/blob/master/autogenerating-colors.txt
