### ISSUE TITLE
light_source = 18 may cause crashes

### ISSUE THREAD

**Issue by Fixer-007** [davisonio/darkage#9]
In recent minetest-dev because of various light glitches and crashes light_source can only be 14 and below.
Quote:
```
        light_source = 0, --[[
        ^ Amount of light emitted by node.
        ^ To set the maximum (currently 14), use the value 'minetest.LIGHT_MAX'.
^ A value outside the range 0 to minetest.LIGHT_MAX causes undefined behavior.]]
````
Dark age lamp uses 18, this crashes minetest for some people on newest minetest-dev.

https://github.com/davisonio/darkage/blob/master/nodes.lua#L226
https://github.com/davisonio/darkage/blob/master/nodes.lua#L356

**Comment by davisonio** [comment]
Thanks for reporting. I've just fixed this by changing the values down to 14!
